improve ci config

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -127,24 +127,67 @@ jobs:
 
       - name: Install dependencies
         run: |
-          poetry check
           poetry config virtualenvs.create false
+          poetry check
           poetry install
 
       - name: Build the Stack
-        run: sugar build --all
+        run: sugar build
 
-      # - name: Build the docs
-      #   run: docker compose -f docker-compose.docs.yml build docs
+      - name: Containers configuration
+        run: sugar config
 
-      # - name: Check DB Migrations
-      #   run: docker compose -f docker-compose.dev.yaml run --rm django python manage.py makemigrations --check
+      # - name: Migrate containers
+      #  run: makim django.migrate
 
-      # - name: Run DB Migrations
-      #   run: docker compose -f docker-compose.dev.yaml run --rm django python manage.py migrate
+      # - name: Check migration files
+      #   if: ${{ success() || failure() }}
+      #   run: makim --verbose django.makemigrations --check
 
-      # - name: Run Django Tests
-      #   run: docker compose -f docker-compose.dev.yaml run django pytest
+      # - name: Run tests FrontEnd
+      #   run: makim --verbose tests.coverage-gen-data --append
 
-      # - name: Tear down the Stack
-      #   run: docker compose -f docker-compose.dev.yaml down
+      - name: Generate logs
+        if: ${{ failure() }}
+        run: |
+          sugar logs --all > /tmp/containers-services.log
+
+      # - name: Set coverage report
+      #   id: parse-coverage-report
+      #   run: |
+      #       COVERAGE_REPORT=$(makim tests.coverage-report)
+      #       COVERAGE_PERCENTAGE=$(echo $COVERAGE_REPORT | grep -oP "TOTAL.* \K(\d{1,3})%")
+      #       COVERAGE_PERCENTAGE=${COVERAGE_PERCENTAGE%?}
+      #       STATE=$(if ((COVERAGE_PERCENTAGE<50)); then echo "critical"; elif ((50<=COVERAGE_PERCENTAGE && COVERAGE_PERCENTAGE<=74)); then echo "yellow"; elif ((75<=COVERAGE_PERCENTAGE)); then echo "success"; fi)
+      #       COVERAGE_REPORT="${COVERAGE_REPORT//'%'/'%25'}"
+      #       COVERAGE_REPORT="${COVERAGE_REPORT//$'\n'/'%0A'}"
+      #       COVERAGE_REPORT="${COVERAGE_REPORT//$'\r'/'%0D'}"
+      #       DABGE="https://img.shields.io/static/v1?label=Code%20Coverage&message=${COVERAGE_PERCENTAGE}%&color=${STATE}"
+      #       echo "::set-output name=COVERAGE_REPORT::$COVERAGE_REPORT"
+      #       echo "::set-output name=DABGE::$DABGE"
+
+      # - uses: mshick/add-pr-comment@v1
+      #   with:
+      #     message: |
+      #       ![Code Coverage](${{ steps.parse-coverage-report.outputs.DABGE }})
+      #       ```
+      #       ${{ steps.parse-coverage-report.outputs.COVERAGE_REPORT }}
+      #       ```
+      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
+      #     repo-token-user-login: 'github-actions[bot]'
+
+      - name: Archive log artifacts
+        uses: actions/upload-artifact@v3
+        if: ${{ failure() }}
+        with:
+          name: test-containers-services
+          path: /tmp/containers-services.log
+
+      - name: Setup tmate session
+        if: "${{ failure() && (contains(github.event.pull_request.labels.*.name, 'ci:enable-debugging')) }}"
+        uses: mxschmitt/action-tmate@v3
+
+      - name: Stop services
+        run: |
+          sugar stop
+          sugar down --options --volumes
